apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: boundary
  name: boundary
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: boundary
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: boundary
    spec:
      containers:
        - args:
            - server
            - -config
            - /boundary/boundary.hcl
          env:
            - name: BOUNDARY_PG_URL
              value: postgresql://postgres:postgres@db/boundary?sslmode=disable
            - name: HOSTNAME
              value: boundary
          image: hashicorp/boundary:0.7.1
          livenessProbe:
            exec:
              command:
                - wget
                - -O-
                - http://boundary:9200
            failureThreshold: 5
            periodSeconds: 3
            timeoutSeconds: 5
          name: boundary
          ports:
            - containerPort: 9200
            - containerPort: 9201
            - containerPort: 9202
          resources: {}
          volumeMounts:
            - mountPath: /boundary/
              name: boundary-claim0
      restartPolicy: Always
      volumes:
        - name: boundary-claim0
          persistentVolumeClaim:
            claimName: boundary-claim0
status: {}
