apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: boundary-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
